apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-circuit-breaker
spec:
  host: redis.voteapp.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1