apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote-service
spec:
  selector:
    name: vote-pod
  ports:
  - port: 80
    name: http # It is the naming convention followed by Istio, In case you don't follow this naming convention, You'll get some warnings in the logs.
    targetPort: 80
    nodePort: 30112
  type: NodePort