apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
spec:
  selector:
    name: postgres-pod
  ports:
    - protocol: TCP
      name: tcp-postgres # It is the naming convention followed by Istio, In case you don't follow this naming convention, You'll get some warnings in the logs.
      port: 5432
      targetPort: 5432
  type: ClusterIP